import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });
const poppins=Poppins({subsets:["latin"],weight:"400"})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-secondary-300 relative">

        <main className={poppins.className}>
        <Navbar/>
        {children}
        </main>
        
     
        
      </body>
      
    </html>
  );
}
